import { spawn } from 'node:child_process'
import { availableParallelism } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import ts from 'typescript'

const frontendRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = join(frontendRoot, 'src', 'App.test.tsx')
const shardPattern = /^App\.shard-\d+\.test\.tsx$/
const relatedMode = process.argv.includes('--related')
const quickMode = process.argv.includes('--quick')
const forwardedArgs = process.argv.slice(2).filter((argument) => !['--ci', '--quick', '--related'].includes(argument))
const isCi = process.argv.includes('--ci') || process.env.CI === 'true'
const defaultParallelism = Math.max(2, Math.min(4, Math.floor(availableParallelism() / 2)))
const quickParallelism = Math.max(2, Math.min(8, availableParallelism()))
const shardCount = readPositiveInteger(process.env.VITEST_APP_SHARDS, defaultParallelism)
const workerCount = readPositiveInteger(
  process.env.VITEST_MAX_WORKERS,
  quickMode ? quickParallelism : isCi ? 4 : defaultParallelism,
)
let child

cleanupGeneratedShards()

try {
  if (quickMode) {
    console.log(`Vitest quick development suite; workers: ${workerCount}. Full App workflows are skipped.`)
  } else {
    generateAppShards()
  }

  const vitestCli = join(frontendRoot, 'node_modules', 'vitest', 'vitest.mjs')
  const args = [
    vitestCli,
    relatedMode ? 'related' : 'run',
    ...(relatedMode ? ['--run'] : []),
    '--exclude',
    'src/App.test.tsx',
    `--maxWorkers=${workerCount}`,
    '--slowTestThreshold=1000',
    ...forwardedArgs,
  ]

  const exitCode = await new Promise((resolveExit, reject) => {
    child = spawn(process.execPath, args, {
      cwd: frontendRoot,
      env: { ...process.env, VITEST_MAX_WORKERS: String(workerCount) },
      stdio: 'inherit',
    })
    child.once('error', reject)
    child.once('exit', (code, signal) => {
      if (signal) {
        reject(new Error(`Vitest stopped by signal ${signal}.`))
        return
      }
      resolveExit(code ?? 1)
    })
  })

  process.exitCode = exitCode
} catch (error) {
  console.error(error instanceof Error ? error.message : error)
  process.exitCode = 1
} finally {
  cleanupGeneratedShards()
}

function generateAppShards() {
  const source = readFileSync(sourcePath, 'utf8')
  const sourceFile = ts.createSourceFile(sourcePath, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX)
  const testStatements = findRootTestStatements(sourceFile)

  if (testStatements.length === 0) {
    throw new Error('App.test.tsx does not contain root test cases to shard.')
  }

  const assignments = balanceTests(testStatements, shardCount)
  const assignedTests = new Set(assignments.flat())
  if (assignedTests.size !== testStatements.length) {
    throw new Error(`Expected ${testStatements.length} unique App tests, assigned ${assignedTests.size}.`)
  }

  assignments.forEach((selectedTests, index) => {
    const selected = new Set(selectedTests)
    let shardSource = source
    const removedRanges = testStatements
      .filter((statement) => !selected.has(statement))
      .map((statement) => [statement.getFullStart(), statement.end])
      .sort((left, right) => right[0] - left[0])

    for (const [start, end] of removedRanges) {
      shardSource = `${shardSource.slice(0, start)}${shardSource.slice(end)}`
    }

    const shardPath = join(frontendRoot, 'src', `App.shard-${index + 1}.test.tsx`)
    writeFileSync(shardPath, `// Generated by scripts/run-vitest.mjs. Do not edit.\n${shardSource}`, 'utf8')
  })

  console.log(`Vitest: ${testStatements.length} App scenarios split into ${assignments.length} files; workers: ${workerCount}.`)
}

function findRootTestStatements(sourceFile) {
  const describeStatement = sourceFile.statements.find((statement) => {
    if (!ts.isExpressionStatement(statement) || !ts.isCallExpression(statement.expression)) {
      return false
    }
    return ts.isIdentifier(statement.expression.expression) && statement.expression.expression.text === 'describe'
  })

  if (!describeStatement || !ts.isExpressionStatement(describeStatement) || !ts.isCallExpression(describeStatement.expression)) {
    return []
  }

  const suite = describeStatement.expression.arguments.find(
    (argument) => (ts.isArrowFunction(argument) || ts.isFunctionExpression(argument)) && ts.isBlock(argument.body),
  )
  if (!suite || (!ts.isArrowFunction(suite) && !ts.isFunctionExpression(suite)) || !ts.isBlock(suite.body)) {
    return []
  }

  return suite.body.statements.filter((statement) => {
    if (!ts.isExpressionStatement(statement) || !ts.isCallExpression(statement.expression)) {
      return false
    }
    return hasRunnableRoot(statement.expression.expression)
  })
}

function hasRunnableRoot(expression) {
  if (ts.isIdentifier(expression)) {
    return ['it', 'test', 'describe'].includes(expression.text)
  }
  if (ts.isPropertyAccessExpression(expression) || ts.isElementAccessExpression(expression)) {
    return hasRunnableRoot(expression.expression)
  }
  if (ts.isCallExpression(expression) || ts.isTaggedTemplateExpression(expression)) {
    return hasRunnableRoot(expression.expression)
  }
  return false
}

function balanceTests(testStatements, count) {
  const buckets = Array.from({ length: Math.min(count, testStatements.length) }, () => ({ weight: 0, tests: [] }))
  const weightedTests = [...testStatements]
    .map((statement) => ({ statement, weight: statement.end - statement.getFullStart() }))
    .sort((left, right) => right.weight - left.weight)

  for (const entry of weightedTests) {
    const bucket = buckets.reduce((lightest, candidate) => candidate.weight < lightest.weight ? candidate : lightest)
    bucket.tests.push(entry.statement)
    bucket.weight += entry.weight
  }

  return buckets.map((bucket) => bucket.tests)
}

function cleanupGeneratedShards() {
  for (const name of readdirSync(join(frontendRoot, 'src'))) {
    if (shardPattern.test(name)) {
      rmSync(join(frontendRoot, 'src', name), { force: true })
    }
  }
}

function readPositiveInteger(value, fallback) {
  const parsed = Number.parseInt(value ?? '', 10)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback
}

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.once(signal, () => {
    child?.kill(signal)
    cleanupGeneratedShards()
    process.exit(1)
  })
}
