// <auto-generated />
using System;
using GarageBalance.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarageBalance.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GarageBalanceDbContext))]
    [Migration("20260723002908_RemoveDemoDatasetFromWorkingDatabases")]
    partial class RemoveDemoDatasetFromWorkingDatabases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageBalance.Api.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ActionKind")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RelatedAccountingMonth")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RelatedCounterpartyId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RelatedCounterpartyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RelatedDocumentId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RelatedDocumentNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RelatedGarageId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RelatedGarageNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Section")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ActionKind");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RelatedAccountingMonth");

                    b.HasIndex("RelatedCounterpartyId");

                    b.HasIndex("RelatedCounterpartyName");

                    b.HasIndex("RelatedDocumentId");

                    b.HasIndex("RelatedDocumentNumber");

                    b.HasIndex("RelatedGarageId");

                    b.HasIndex("RelatedGarageNumber");

                    b.HasIndex("Section");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("Section", "ActionKind", "CreatedAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.ChargeServiceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AccrualStartMonth")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasTieredTariff")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IncomeTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMetered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegular")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OverdueGraceDays")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentDueDay")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentDueMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodicityMonths")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HasTieredTariff");

                    b.HasIndex("IncomeTypeId");

                    b.HasIndex("IsMetered");

                    b.HasIndex("IsRegular");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.HasIndex("TariffId");

                    b.ToTable("charge_service_settings", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.ExpenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("expense_types", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.FeeCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AppliesToAllGarages")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IncomeTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OverdueGraceDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncomeTypeId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.HasIndex("StartsOn");

                    b.ToTable("fee_campaigns", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.FeeCampaignGarage", b =>
                {
                    b.Property<Guid>("FeeCampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid");

                    b.HasKey("FeeCampaignId", "GarageId");

                    b.HasIndex("GarageId");

                    b.ToTable("fee_campaign_garages", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InitialElectricityMeterValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("InitialWaterMeterValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.HasIndex("OwnerId");

                    b.ToTable("garages", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.IncomeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DestinationFundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("DestinationFundId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("income_types", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.IrregularPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("irregular_payments", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MeterNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.HasIndex("LastName", "FirstName", "MiddleName");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.StaffDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("staff_departments", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FullName");

                    b.ToTable("staff_members", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChargeServiceSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Inn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChargeServiceSettingId");

                    b.HasIndex("ContactPerson");

                    b.HasIndex("GroupId");

                    b.HasIndex("Inn");

                    b.HasIndex("Name");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.SupplierContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Position")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("Phone");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_contacts", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.SupplierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("supplier_groups", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationBase")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal?>("ElectricityFirstRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ElectricityFirstThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ElectricityFirstTierName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("ElectricitySecondRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ElectricitySecondThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ElectricitySecondTierName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("ElectricityThirdRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ElectricityThirdTierName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ElectricityTiersJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalculationBase");

                    b.HasIndex("EffectiveFrom");

                    b.HasIndex("Name", "EffectiveFrom")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = false");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.Accrual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccountingMonth")
                        .HasColumnType("date");

                    b.Property<int?>("AccountingYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("DueDateNeedsReview")
                        .HasColumnType("boolean");

                    b.Property<string>("DueDateReviewReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("FeeCampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncomeTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IrregularPaymentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("OverdueFromDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountingMonth");

                    b.HasIndex("DueDate");

                    b.HasIndex("FeeCampaignId");

                    b.HasIndex("GarageId");

                    b.HasIndex("IncomeTypeId");

                    b.HasIndex("IrregularPaymentId");

                    b.HasIndex("OverdueFromDate");

                    b.HasIndex("TariffId");

                    b.HasIndex("DueDateNeedsReview", "AccountingMonth");

                    b.HasIndex("GarageId", "FeeCampaignId", "AccountingMonth")
                        .IsUnique()
                        .HasFilter("\"IsCanceled\" = false AND \"FeeCampaignId\" IS NOT NULL");

                    b.HasIndex("GarageId", "IrregularPaymentId", "AccountingMonth")
                        .IsUnique()
                        .HasFilter("\"IsCanceled\" = false AND \"IrregularPaymentId\" IS NOT NULL");

                    b.HasIndex("GarageId", "OverdueFromDate", "IsCanceled");

                    b.HasIndex("GarageId", "IncomeTypeId", "AccountingMonth", "Source")
                        .IsUnique()
                        .HasFilter("\"IsCanceled\" = false AND \"IrregularPaymentId\" IS NULL AND \"FeeCampaignId\" IS NULL");

                    b.HasIndex("GarageId", "IncomeTypeId", "AccountingYear", "IsCanceled");

                    b.ToTable("accruals", null, t =>
                        {
                            t.HasCheckConstraint("CK_accruals_AccountingYear_Range", "\"AccountingYear\" IS NULL OR (\"AccountingYear\" >= 1900 AND \"AccountingYear\" <= 9999)");
                        });
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.AccrualPaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccrualId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinancialOperationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccrualId");

                    b.HasIndex("FinancialOperationId", "AccrualId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("accrual_payment_allocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_accrual_payment_allocations_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.FinancialOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccountingMonth")
                        .HasColumnType("date");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ExpenseTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GarageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncomeTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("OperationDate")
                        .HasColumnType("date");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountingMonth");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("GarageId");

                    b.HasIndex("IncomeTypeId");

                    b.HasIndex("OperationDate");

                    b.HasIndex("OperationKind");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("IsCanceled", "OperationKind");

                    b.HasIndex("OperationKind", "OperationDate", "DocumentNumber")
                        .IsUnique()
                        .HasFilter("\"IsCanceled\" = false AND \"DocumentNumber\" IS NOT NULL");

                    b.ToTable("financial_operations", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowOperations")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.FundOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCashToBankTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("SourceFinancialOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FundId");

                    b.HasIndex("IsCanceled");

                    b.HasIndex("OperationKind");

                    b.HasIndex("SourceFinancialOperationId")
                        .IsUnique()
                        .HasFilter("\"SourceFinancialOperationId\" IS NOT NULL");

                    b.ToTable("fund_operations", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccountingMonth")
                        .HasColumnType("date");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Consumption")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasGapWarning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<string>("MeterKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("PreviousValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountingMonth");

                    b.HasIndex("GarageId");

                    b.HasIndex("ReadingDate");

                    b.HasIndex("GarageId", "MeterKind", "AccountingMonth")
                        .IsUnique()
                        .HasFilter("\"IsCanceled\" = false");

                    b.HasIndex("MeterKind", "AccountingMonth", "GarageId")
                        .HasFilter("\"IsCanceled\" = false");

                    b.ToTable("meter_readings", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.SupplierAccrual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccountingMonth")
                        .HasColumnType("date");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ExpenseTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountingMonth");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("SupplierId", "ExpenseTypeId", "AccountingMonth", "Source", "DocumentNumber")
                        .IsUnique()
                        .HasFilter("\"IsCanceled\" = false");

                    b.ToTable("supplier_accruals", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Import.AccessImportCreatedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessImportRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RollbackReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RollbackStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("RolledBackAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RolledBackByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SourceExternalId")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("SourceRowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TargetDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("AccessImportRunId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RollbackStatus");

                    b.HasIndex("SourceRowHash");

                    b.HasIndex("SourceSystem", "SourceEntityType");

                    b.HasIndex("AccessImportRunId", "TargetEntityType", "TargetEntityId")
                        .IsUnique();

                    b.ToTable("access_import_created_records", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Import.AccessImportQuarantineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessImportRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReasonMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ResolutionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RowSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccessImportRunId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RowHash");

                    b.HasIndex("Status");

                    b.HasIndex("SourceSystem", "EntityType");

                    b.ToTable("access_import_quarantine_items", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Import.AccessImportRowFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessImportRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("FingerprintKey")
                        .IsRequired()
                        .HasMaxLength(520)
                        .HasColumnType("character varying(520)");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TargetEntityId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("AccessImportRunId");

                    b.HasIndex("FingerprintKey")
                        .IsUnique();

                    b.HasIndex("SourceSystem", "EntityType");

                    b.ToTable("access_import_row_fingerprints", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Import.AccessImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("PassedChecks")
                        .HasColumnType("integer");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TotalChecks")
                        .HasColumnType("integer");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentSha256");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("access_import_runs", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Import.AccessImportRunLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessImportRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("AccessImportRunId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("AccessImportRunId", "CreatedAtUtc");

                    b.ToTable("access_import_run_log_entries", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Integrations.IntegrationSecretSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedSettingKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("NormalizedProvider", "NormalizedSettingKey")
                        .IsUnique()
                        .HasDatabaseName("IX_integration_secret_settings_provider_key");

                    b.ToTable("integration_secret_settings", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Releases.AppReleaseRecord", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("ReleaseId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.HasIndex("IsPublished", "PublishedAt");

                    b.ToTable("app_releases", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Settings.ApplicationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("application_settings", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Users.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("app_roles", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Users.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("app_user_roles", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Workflows.FormState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("form_states", (string)null);
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.ChargeServiceSetting", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IncomeType");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.FeeCampaign", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncomeType");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.FeeCampaignGarage", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.FeeCampaign", "FeeCampaign")
                        .WithMany("ParticipantGarages")
                        .HasForeignKey("FeeCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeCampaign");

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Garage", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Owner", "Owner")
                        .WithMany("Garages")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.IncomeType", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Finance.Fund", "DestinationFund")
                        .WithMany()
                        .HasForeignKey("DestinationFundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationFund");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.StaffMember", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.StaffDepartment", "Department")
                        .WithMany("StaffMembers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Supplier", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.ChargeServiceSetting", "ChargeServiceSetting")
                        .WithMany()
                        .HasForeignKey("ChargeServiceSettingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.SupplierGroup", "Group")
                        .WithMany("Suppliers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargeServiceSetting");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.SupplierContact", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.Accrual", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.FeeCampaign", "FeeCampaign")
                        .WithMany()
                        .HasForeignKey("FeeCampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.IrregularPayment", "IrregularPayment")
                        .WithMany()
                        .HasForeignKey("IrregularPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeeCampaign");

                    b.Navigation("Garage");

                    b.Navigation("IncomeType");

                    b.Navigation("IrregularPayment");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.AccrualPaymentAllocation", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Finance.Accrual", "Accrual")
                        .WithMany()
                        .HasForeignKey("AccrualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Finance.FinancialOperation", "FinancialOperation")
                        .WithMany()
                        .HasForeignKey("FinancialOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accrual");

                    b.Navigation("FinancialOperation");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.FinancialOperation", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.StaffMember", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExpenseType");

                    b.Navigation("Garage");

                    b.Navigation("IncomeType");

                    b.Navigation("StaffMember");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.FundOperation", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Finance.Fund", "Fund")
                        .WithMany("Operations")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Finance.FinancialOperation", "SourceFinancialOperation")
                        .WithMany()
                        .HasForeignKey("SourceFinancialOperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fund");

                    b.Navigation("SourceFinancialOperation");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.MeterReading", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.SupplierAccrual", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Dictionaries.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Users.AppUserRole", b =>
                {
                    b.HasOne("GarageBalance.Api.Domain.Users.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageBalance.Api.Domain.Users.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.FeeCampaign", b =>
                {
                    b.Navigation("ParticipantGarages");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.Owner", b =>
                {
                    b.Navigation("Garages");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.StaffDepartment", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Dictionaries.SupplierGroup", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Finance.Fund", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Users.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GarageBalance.Api.Domain.Users.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
